const date=document.getElementById("date");if(date)date.min=new Date().toISOString().slice(0,10);
function toggleMenu(){document.getElementById("navlinks").classList.toggle("open")}
function chooseService(s){const el=document.getElementById("service");if(el){el.value=[...el.options].find(o=>o.textContent.includes(s))?.value||""}document.getElementById("booking").scrollIntoView({behavior:"smooth"})}
function book(e){e.preventDefault();document.getElementById("msg").textContent="✨ Thank you! Your appointment request is ready. Online confirmation + Telegram synchronization will be connected in the next stage."}
function addPhotos(e,key,input){const files=[...e.target.files];const box=document.getElementById(key+"-photos");if(!box)return;files.forEach(f=>{const r=new FileReader();r.onload=()=>{const img=document.createElement("img");img.src=r.result;img.title=f.name;box.appendChild(img);let old=JSON.parse(localStorage.getItem("maya_"+key)||"[]");old.push(r.result);localStorage.setItem("maya_"+key,JSON.stringify(old.slice(-30)))};r.readAsDataURL(f)});input.value=""}
function addGallery(e){const grid=document.getElementById("galleryGrid");[...e.target.files].forEach(f=>{const r=new FileReader();r.onload=()=>{const t=document.createElement("div");t.className="galleryTile";t.dataset.cat="Owner";t.style.backgroundImage=`url("${r.result}")`;t.innerHTML="<span>✨ MAYA • OWNER PHOTO</span>";grid.prepend(t)};r.readAsDataURL(f)});e.target.value=""}
const defaults=[["assets/hair.svg","Hair"],["assets/nails.svg","Nails"],["assets/makeup.svg","Makeup"],["assets/lashes.svg","Lashes"],["assets/spa.svg","Spa"],["assets/extensions.svg","Extensions"],["assets/hair.svg","Hair"],["assets/nails.svg","Nails"],["assets/makeup.svg","Makeup"],["assets/spa.svg","Spa"]];
const grid=document.getElementById("galleryGrid");defaults.forEach(([src,cat])=>{const t=document.createElement("div");t.className="galleryTile";t.dataset.cat=cat;t.style.backgroundImage=`url("${src}")`;t.innerHTML=`<span>${cat} • MAYA BEAUTY</span>`;grid.appendChild(t)});
document.querySelectorAll(".filters button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("sel"));b.classList.add("sel");const f=b.dataset.filter;document.querySelectorAll(".galleryTile").forEach(x=>x.style.display=(f==="all"||x.dataset.cat===f)?"block":"none")}));
document.querySelectorAll(".card").forEach((c,i)=>{c.style.opacity=0;c.style.transform="translateY(18px)";const ob=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting){c.style.transition="all .65s ease";c.style.opacity=1;c.style.transform="none";ob.disconnect()}}));ob.observe(c)});
